# Generated by Django 3.2.9 on 2021-11-18 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('picture', models.ImageField(upload_to='', verbose_name='изображение инвентаря')),
            ],
            options={
                'verbose_name': 'инвентарь для хранения',
                'verbose_name_plural': 'хранимые вещи',
            },
        ),
        migrations.CreateModel(
            name='InventoryPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_week', models.PositiveIntegerField(verbose_name='цена за неделю')),
                ('price_per_month', models.PositiveIntegerField(verbose_name='цена за месяц')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.inventory', verbose_name='инвентарь')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('description', models.TextField(blank=True, verbose_name='короткое описание')),
                ('picture', models.ImageField(upload_to='', verbose_name='изображение')),
                ('first_square_meter_price', models.PositiveIntegerField(verbose_name='цена за первый метр')),
                ('rest_meters_price', models.PositiveIntegerField(verbose_name='цена за каждый последующий метр')),
                ('stored_items', models.ManyToManyField(through='storage.InventoryPriceList', to='storage.Inventory', verbose_name='хранимые вещи')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_size', models.IntegerField(blank=True, null=True, verbose_name='размер бокса')),
                ('price', models.PositiveIntegerField(verbose_name='цена хранения')),
                ('start_date', models.DateField(verbose_name='дата начала услуг')),
                ('end_date', models.DateField(verbose_name='дата окончания услуг')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_rental_orders', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('inventory', models.ManyToManyField(to='storage.Inventory', verbose_name='вещи для хранения')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='storage.storage', verbose_name='склад')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='inventorypricelist',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storage', verbose_name='склад'),
        ),
    ]
