# Generated by Django 3.2.9 on 2021-11-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20211119_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название города')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
            ],
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(max_length=150, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='storage',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.town', verbose_name='город'),
        ),
    ]
