# Generated by Django 3.2.9 on 2021-11-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20211119_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'город', 'verbose_name_plural': 'города'},
        ),
    ]
