# Generated by Django 3.2.9 on 2021-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заказ не оплачен'), (1, 'Заказ оплачен')], default=0, verbose_name='Статус оплаты заказа'),
        ),
    ]
