# Generated by Django 3.2.9 on 2021-11-18 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Серия и номер паспорта'),
        ),
    ]
