# Generated by Django 3.2.9 on 2021-11-18 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)], verbose_name='Серия и номер паспорта'),
        ),
    ]
