# Generated by Django 3.2.9 on 2021-11-23 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Серия и номер паспорта'),
        ),
    ]
