# Generated by Django 3.2.9 on 2021-11-23 11:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(default=1234567890, max_length=10, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Серия и номер паспорта'),
            preserve_default=False,
        ),
    ]
